### ISSUE TITLE
TileManager to generate map

### ISSUE THREAD

**Issue by pzyu** [pzyu/gip2017#3]
5x5 map can be represented in a text file without the headers
A fixed path can be given by creating a path of `1`s from the starting point **A0** to end **E4**

|   | A | B | C | D | E |
|---|---|---|---|---|---|
| **0** | `1` | 0 | 0 | 0 | 0 |
| **1** | `1` | `1` | 0 | 0 | 0 |
| **2** | 0 | `1` | `1` | 0 | 0 |
| **3** | 0 | 0 | `1` | 0 | 0 |
| **4** | 0 | 0 | `1` | `1` | `1` |

Tiles with 1 can be assigned with a random tile that is connected to its adjacent tiles
Tiles with 0 can be assigned with any random tile

|   | A | B | C | D | E |
|---|---|---|---|---|---|
| **0** | `║` | ╔ | ╩ | ╠ | ╬ |
| **1** | `╩` | `╬` | ╔ | ╩ | ╠ |
| **2** | ═ | `╠` | `╗` | ═ | ╔ |
| **3** | ╬ | ╔ | `╬` | ╔  | ╠ |
| **4** | ╩ | ═ | `╩` | `═` | `╗` |

Fixed path is still the same

Likewise, relics and enemies can be represented using characters in the desired coordinates

**Comment by ckjr** [comment]
Even mix of tiles (a specific number of each type of tiles).
I.e. At most 1-2 dead ends.

Type of tiles for the opposite corners should be <to be determined>
