### ISSUE TITLE
Decide on controls

### ISSUE THREAD

**Issue by pzyu** [pzyu/gip2017#5]
Perhaps more intuitive to keep all controls on the mouse, rather than having certain actions done on the keyboard, and some on the mouse.

Also a lot easier to port to mobile if necessary

Idea 1:

Action | Controls
--------|---------
Moving player | Left clicking on any adjacent tile
Twisting tiles | Dragging motion from any tile
Rotating tile | Right clicking on active tile

Idea 2:

Action | Controls
--------|---------
Moving player | WASD
Twisting tiles | Make 2x2 selection based on mouse position, then drag to twist
Rotating tile | Clicking twice to select a single tile, then rotate

Idea 3:

Action | Controls
--------|---------
Moving player | WASD
Twisting tiles | Selecting/dragging order of tiles
Rotating tile | Clicking on left/right arrows that hover over player

**Comment by ckjr** [comment]
My suggestion:

Click once to determine the 2x2 region of squares to target, click twice to get a single square.
Once the square(s) are selected, you can drag them to rotate.

**Comment by pzyu** [comment]
@ckjr How do we determine which 2x2 region? Will the targeted square always be on the top left/right?

**Comment by ckjr** [comment]
We can use this:

Get the relative coordinate of the mouse in the set of tiles = C
We find (C % width) / width. This should give a value between 0 and 1.
We also find floor(C / width). This should give a value between 0 and the number of tiles in a row - 1.
So using this we can pinpoint which tile in the row the mouse is hovering over.

A B C D

To determine which 2x2 region of squares to target, we just see (C % width) / width. 
If it is smaller than 0.5 and Tile B is selected, that means A B are part of the 2x2 region of squares selected. 
If it is bigger than 0.5 and Tile B is selected, that means B C are part of the 2x2 region of squares selected

Then we apply the same calculations along the Y axis to determine the 2x2 region of squares.

**Comment by pzyu** [comment]
Oh so we are calculating the 4 corners of a single tile like:

| **0.0, 0.0** | **0.5, 0.0** |
|---|---|
| **0.0, 0.5** | **0.5, 0.5**|

So if my mouse is over the 0.0, 0.0 region, then it is the bottom right tile of the region above?

**Comment by ckjr** [comment]
Yeah, we are determining which 2x2 region to choose by the mouse distance from the midpoint of the top left tile
